# places prompt information on the right 
format       = """$character"""
right_format = """$all"""

# allows the prompt to be one line
[line_break]
disabled = true

# shows current profile
[username]
show_always = true
format      = "[$user]($style): "

# git status to show the count of files
[git_status]
modified  = "!($count)"
untracked = "?($count)"
staged    = "+($count)"
style     = "bold bright-blue"

# shows current time uncomment to show time
# [time]
# disabled = false
# use_12hr = true
# format   = "[$time]($style)"
# style    = "bold bright-black"

# unwanted information
[cmd_duration]
disabled = true
[aws]
disabled = true
[python]
disabled = true
[java]
disabled = true
