format = """
[](#86BBD8)\
$directory\
[](fg:#86BBD8 bg:#06969A)\
$git_branch\
[](fg:#06969A bg:#33658A)\
$git_status\
[ ](fg:#33658A)\
"""

[directory]
style             = "bg:#86BBD8"
format            = "[ $path ]($style)"
truncation_length = 1

[git_branch]
symbol = ""
style  = "bg:#06969A"
format = '[[ $symbol $branch ](bg:#06969A)]($style)'

[git_status]
style     = "bg:#33658A"
format    = '[[( $all_status$ahead_behind )](bg:#33658A)]($style)'
deleted   = "-($count)"
modified  = "!($count)"
untracked = "?($count)"
staged    = "+($count)"

