format = """
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

[hostname]
ssh_only = false
format   = '[$hostname](bright-blue)[:](bright-black)'

[directory]
style             = "bright-purple"
truncation_length = 1
format            = '[$path]($style)'

[git_branch]
style  = "bright-black"
format = '[\(](bright-black)[$branch]($style)[\)](bright-black)'

[git_status]
style     = "bright-black"
modified  = " "
untracked = " "
staged    = " "
deleted   = " "
renamed   = " "
format    = '([*$renamed$modified$untracked$staged$deleted]($style))'

[character]
success_symbol = "[>](bright-black)"
error_symbol   = "[>](bright-black)"
