format = """
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

[hostname]
ssh_only = false
format   = '[$hostname](bright-purple) '

[directory]
style             = "bright-blue"
truncation_length = 1
format            = '[$path ]($style)'

[git_branch]
symbol = ""
style  = "black"
format = '[$symbol $branch ]($style)'

[git_status]
style     = "black"
format    = '([\[$modified$untracked$staged\]]($style))'
modified  = "!($count)"
untracked = "?($count)"
staged    = "+($count)"

[character]
success_symbol = "[❯](bright-black)"
error_symbol   = "[❯](bright-black)"
