format = """
$directory\
$git_branch\
$git_status\
$character
"""

[directory]
style             = "bright-blue bold"
truncation_length = 1
format            = '[$path ]($style)'

[git_branch]
symbol = ""
style  = "bright-black"
format = '[$symbol $branch ]($style)'

[git_status]
style     = "white"
format    = '([\[$modified$untracked$staged\] ]($style))'
modified  = "!($count)"
untracked = "?($count)"
staged    = "+($count)"

[character]
success_symbol = "[❯](bright-black)"
error_symbol   = "[❯](bright-black)"
