format = """
$directory\
$git_branch\
$git_status\
$character
"""

[directory]
style  = "bright-blue bold"
format = "[$path ]($style)"

[git_branch]
symbol = ""
style  = "bright-black"
format = '[$symbol $branch ]($style)'

[git_status]
style     = "bright-black"
format    = '([\[$modified$untracked$staged\] ](218)($style))'
modified  = "!($count)"
untracked = "?($count)"
staged    = "+($count)"

[character]
success_symbol = "[❯](purple)"
error_symbol   = "[❯](red)"
vicmd_symbol   = "[❮](green)"
