format = """
[](#458588)\
$directory\
$git_branch\
[ ](fg:#458588)\
"""

right_format = """
[](#8EC07C)
$git_status\
$time\
[](#8EC07C)
"""

[directory]
style             = "bg:#458588"
format            = "[ $path ]($style)"
truncation_length = 1

[git_branch]
symbol = ""
style  = "bg:#458588"
format = '[[$symbol on $branch ](bg:#458588)]($style)'

[git_status]
style     = "bg:#8EC07C"
format    = '([\[$modified$untracked$staged(bg:#8EC07C)\] ]($style))'
modified  = "!($count)"
untracked = "?($count)"
staged    = "+($count)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8EC07C"
format = '[[$time](bg:#8EC07C)]($style)'

# | gruvbox | nord   |
# |---------|--------|
# | 458588  | 88C0D0 |
# | 8EC07C  | A3BE8C |
