#!/usr/bin/env bash

main() {
    selectRepo
    startSessionIfNotRunning
    startSessionIfRunning
    switchSessionIfRunning
}

selectRepo() {
    selected=$(find ~/Documents/repos -mindepth 1 -maxdepth 1 -type d | fzf)
    if [[ -z $selected ]]; then
        exit 0
    fi
    selected_name=$(basename "$selected" | tr . _)
    tmux_running=$(pgrep tmux)
}

startSessionIfNotRunning() {
    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        createNewSession
        tmux attach-session -t $selected_name
        exit 0
    fi
}

startSessionIfRunning() {
    if [[ -z $TMUX ]] && [[ -n $tmux_running ]]; then
        if ! tmux has-session -t=$selected_name 2> /dev/null; then
            createNewSession
        fi

        tmux attach-session -t $selected_name
        exit 0
    fi
}

switchSessionIfRunning() {
    if [[ -n $TMUX ]] && [[ -n $tmux_running ]]; then
        if ! tmux has-session -t=$selected_name 2> /dev/null; then
            createNewSession
        fi
    fi

    tmux switch-client -t $selected_name
    exit 0
}

createNewSession() {
    tmux new-session -d -s $selected_name -c $selected 'nvim .'
    tmux rename-window -t $selected_name:1 'vim'
    tmux new-window -d -n 'terminal' -t $selected_name -c $selected
}

main
