# aliases
alias vim="nvim"
alias py="python3"
alias gh="history | grep"
alias ls="ls -l"
alias ..="cd .."
alias ...="cd ../.."

alias gb="git checkout -b"
alias gc="git checkout"
alias ga="git add -A"
alias gc="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gl="git log"
alias gs="git status"
alias gd="git diff"

alias notes="cd /home/nathan/vimwiki/"
alias repos="cd /home/nathan/Documents/repos/"

# command prompt
eval "$(starship init bash)"

