#!/usr/bin/env bash

main() {
    selectRepo
    switchSession
}

selectRepo() {
    selected=$(find ~/Documents/repos -mindepth 1 -maxdepth 1 -type d | fzf)

    if [[ -z $selected ]]; then
        exit 0
    fi
}

switchSession() {
    selected_name=$(basename "$selected" | tr . _)
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        createNewSession
        tmux attach-session -t $selected_name
        exit 0
    fi

    if [[ -z $TMUX ]] && [[ -n $tmux_running ]]; then
        checkIfSessionExists
        tmux attach-session -t $selected_name
        exit 0
    fi

    if [[ -n $TMUX ]] && [[ -n $tmux_running ]]; then
        checkIfSessionExists
        tmux switch-client -t $selected_name
        exit 0
    fi
}

checkIfSessionExists() {
    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        createNewSession
    fi
}

createNewSession() {
    tmux new-session -d -s $selected_name -c $selected 'nvim .'
    tmux rename-window -t $selected_name:1 'vim'
    tmux new-window -d -n 'terminal' -t $selected_name -c $selected
}

main
